# config/validator/validation.yaml
App\Form\Model\DestinoDto:
  properties:
    usuario:
      - NotBlank: ~
      - Length:
          min: 2
          max: 50
          minMessage: 'Your first name must be at least {{ limit }} characters long'
          maxMessage: 'Your first name cannot be longer than {{ limit }} characters'
