version: '3'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db_dni_app_api:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - symfony
  php:
    build:
      context: php
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ../:/var/www/dniappapi/
    networks:
      - symfony
  nginx:
    build:
      context: nginx
    volumes:
      - ../:/var/www/dniappapi/
    ports:
      - 80:80
    networks:
      - symfony

volumes:
  dniAppApiback_app_sync:
    external: true
  db_dni_app_api:

networks:
  symfony: